//
// Generated by Microsoft (R) HLSL Shader Compiler 6.3.9600.16384
//
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_POSITION              0   xyzw        0      POS   float       
// POSITION                 0   xyz         1     NONE   float       
// NORMAL                   0   xyz         2     NONE   float       
// TEXCOORD                 1   xyzw        3     NONE   float       
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_Target                0   xyzw        0   TARGET   float   xyzw
//
ps_5_0
dcl_globalFlags refactoringAllowed | skipOptimization
dcl_output o0.xyzw
//
// Initial variable locations:
//   v0.x <- input.PosH.x; v0.y <- input.PosH.y; v0.z <- input.PosH.z; v0.w <- input.PosH.w; 
//   v1.x <- input.PosW.x; v1.y <- input.PosW.y; v1.z <- input.PosW.z; 
//   v2.x <- input.NorW.x; v2.y <- input.NorW.y; v2.z <- input.NorW.z; 
//   v3.x <- input.ShadowH.x; v3.y <- input.ShadowH.y; v3.z <- input.ShadowH.z; v3.w <- input.ShadowH.w; 
//   o0.x <- <PS return value>.x; o0.y <- <PS return value>.y; o0.z <- <PS return value>.z; o0.w <- <PS return value>.w
//
#line 106 "D:\Projects\Demo\ShadowDemo\ShadowDemo\Shaders\DemoShader.hlsl"
nop 
nop 
nop 

#line 113
nop 

#line 119
nop 

#line 128
mov o0.xyzw, l(1.000000,0,0,1.000000)
ret 
// Approximately 7 instruction slots used
