//
// Generated by Microsoft (R) HLSL Shader Compiler 6.3.9600.16384
//
//
// Buffer Definitions: 
//
// cbuffer cbPerObject
// {
//
//   float4x4 matWorld;                 // Offset:    0 Size:    64
//   float4x4 matWVP;                   // Offset:   64 Size:    64
//   
//   struct Material
//   {
//       
//       float4 Ambient;                // Offset:  128
//       float4 Diffuse;                // Offset:  144
//       float4 Specular;               // Offset:  160
//       float4 Reflect;                // Offset:  176
//
//   } material;                        // Offset:  128 Size:    64 [unused]
//   float4x4 matWorldInvTranspose;     // Offset:  192 Size:    64
//   float4x4 lightWVPT;                // Offset:  256 Size:    64
//   bool isInstancing;                 // Offset:  320 Size:     4
//   float padding[3];                  // Offset:  336 Size:    36 [unused]
//
// }
//
//
// Resource Bindings:
//
// Name                                 Type  Format         Dim Slot Elements
// ------------------------------ ---------- ------- ----------- ---- --------
// cbPerObject                       cbuffer      NA          NA    3        1
//
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// POSITION                 0   xyz         0     NONE   float   xyz 
// NORMAL                   0   xyz         1     NONE   float   xyz 
// WORLD                    0   xyzw        2     NONE   float   xyz 
// WORLD                    1   xyzw        3     NONE   float   xyz 
// WORLD                    2   xyzw        4     NONE   float   xyz 
// WORLD                    3   xyzw        5     NONE   float   xyz 
// SV_InstanceID            0   x           6   INSTID    uint       
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_POSITION              0   xyzw        0      POS   float   xyzw
// POSITION                 0   xyz         1     NONE   float   xyz 
// NORMAL                   0   xyz         2     NONE   float   xyz 
// TEXCOORD                 1   xyzw        3     NONE   float   xyzw
//
vs_5_0
dcl_globalFlags refactoringAllowed | skipOptimization
dcl_constantbuffer cb3[21], immediateIndexed
dcl_input v0.xyz
dcl_input v1.xyz
dcl_input v2.xyz
dcl_input v3.xyz
dcl_input v4.xyz
dcl_input v5.xyz
dcl_output_siv o0.xyzw, position
dcl_output o1.xyz
dcl_output o2.xyz
dcl_output o3.xyzw
dcl_temps 5
//
// Initial variable locations:
//   v0.x <- input.PosL.x; v0.y <- input.PosL.y; v0.z <- input.PosL.z; 
//   v1.x <- input.NorL.x; v1.y <- input.NorL.y; v1.z <- input.NorL.z; 
//   v2.x <- input.World._m00; v2.y <- input.World._m01; v2.z <- input.World._m02; v2.w <- input.World._m03; 
//   v3.x <- input.World._m10; v3.y <- input.World._m11; v3.z <- input.World._m12; v3.w <- input.World._m13; 
//   v4.x <- input.World._m20; v4.y <- input.World._m21; v4.z <- input.World._m22; v4.w <- input.World._m23; 
//   v5.x <- input.World._m30; v5.y <- input.World._m31; v5.z <- input.World._m32; v5.w <- input.World._m33; 
//   v6.x <- input.InstanceId; 
//   o3.x <- <VS return value>.ShadowH.x; o3.y <- <VS return value>.ShadowH.y; o3.z <- <VS return value>.ShadowH.z; o3.w <- <VS return value>.ShadowH.w; 
//   o2.x <- <VS return value>.NorW.x; o2.y <- <VS return value>.NorW.y; o2.z <- <VS return value>.NorW.z; 
//   o1.x <- <VS return value>.PosW.x; o1.y <- <VS return value>.PosW.y; o1.z <- <VS return value>.PosW.z; 
//   o0.x <- <VS return value>.PosH.x; o0.y <- <VS return value>.PosH.y; o0.z <- <VS return value>.PosH.z; o0.w <- <VS return value>.PosH.w
//
#line 87 "D:\Projects\Demo\ShadowDemo\ShadowDemo\Shaders\DemoShader.hlsl"
mov r0.xyz, v0.xyzx  // r0.x <- posL.x; r0.y <- posL.y; r0.z <- posL.z
ine r1.x, l(0, 0, 0, 0), cb3[20].x
if_nz r1.x
  mul r1.xyz, v0.xxxx, v2.xyzx
  mul r2.xyz, v0.yyyy, v3.xyzx
  add r1.xyz, r1.xyzx, r2.xyzx
  mul r2.xyz, v0.zzzz, v4.xyzx
  add r1.xyz, r1.xyzx, r2.xyzx
  mul r2.xyz, v5.xyzx, l(1.000000, 1.000000, 1.000000, 0.000000)
  add r0.xyz, r1.xyzx, r2.xyzx
endif 
mov r0.w, l(1.000000)
dp4 r1.x, r0.xyzw, cb3[0].xyzw  // r1.x <- output.PosW.x
dp4 r1.y, r0.xyzw, cb3[1].xyzw  // r1.y <- output.PosW.y
dp4 r1.z, r0.xyzw, cb3[2].xyzw  // r1.z <- output.PosW.z
dp3 r2.x, v1.xyzx, cb3[12].xyzx  // r2.x <- output.NorW.x
dp3 r2.y, v1.xyzx, cb3[13].xyzx  // r2.y <- output.NorW.y
dp3 r2.z, v1.xyzx, cb3[14].xyzx  // r2.z <- output.NorW.z
dp4 r3.x, r0.xyzw, cb3[4].xyzw  // r3.x <- output.PosH.x
dp4 r3.y, r0.xyzw, cb3[5].xyzw  // r3.y <- output.PosH.y
dp4 r3.z, r0.xyzw, cb3[6].xyzw  // r3.z <- output.PosH.z
dp4 r3.w, r0.xyzw, cb3[7].xyzw  // r3.w <- output.PosH.w
dp4 r4.x, r0.xyzw, cb3[16].xyzw  // r4.x <- output.ShadowH.x
dp4 r4.y, r0.xyzw, cb3[17].xyzw  // r4.y <- output.ShadowH.y
dp4 r4.z, r0.xyzw, cb3[18].xyzw  // r4.z <- output.ShadowH.z
dp4 r4.w, r0.xyzw, cb3[19].xyzw  // r4.w <- output.ShadowH.w
mov o0.xyzw, r3.xyzw
mov o3.xyzw, r4.xyzw
mov o1.xyz, r1.xyzx
mov o2.xyz, r2.xyzx
ret 
// Approximately 31 instruction slots used
